# @generated by scripts/generate_protocol.py; do not edit.

RPC_PROTOCOL = "agenttab.rpc"
RPC_VERSION = 1
RPC_SUPPORTED_VERSIONS = (
    1,
)
RPC_FEATURES = (
    "commit_staging_v1",
    "idempotency_v1",
    "operation_outcomes_v1",
    "task_resume_v1",
)
RPC_METHODS = (
    "browser_open",
    "browser_snapshot",
    "browser_act",
    "browser_wait",
    "browser_tabs",
    "browser_handoff",
    "browser_commit",
    "browser_developer",
    "agenttab.status",
)
MUTATIONS = frozenset((
    "browser_open",
    "browser_act",
    "browser_handoff",
    "browser_commit",
    "browser_developer",
))
OUTCOMES = (
    "completed",
    "not_started",
    "unknown",
    "needs_user",
    "commit_required",
)
CLIENT_TO_HOST_MAX_BYTES = 1048576
HOST_TO_CLIENT_MAX_BYTES = 1048576
