// @generated by scripts/generate_protocol.py; do not edit.

pub const RPC_PROTOCOL: &str = "agenttab.rpc";
pub const NATIVE_PROTOCOL: &str = "agenttab.native";
pub const RPC_VERSION: u16 = 1;
pub const NATIVE_VERSION: u16 = 1;
pub const PROTOCOL_VERSION: u16 = RPC_VERSION;
pub const RPC_SUPPORTED_VERSIONS: &[u16] = &[1];
pub const NATIVE_SUPPORTED_VERSIONS: &[u16] = &[1];
pub const RPC_FEATURES: &[&str] = &[
    "commit_staging_v1",
    "idempotency_v1",
    "operation_outcomes_v1",
    "task_resume_v1",
];
pub const NATIVE_FEATURES: &[&str] = &[
    "commit_staging_v1",
    "disconnect_recovery_v1",
    "event_ack_v1",
    "inventory_reconciliation_v1",
];
pub const RPC_METHOD_NAMES: &[&str] = &[
    "browser_open",
    "browser_snapshot",
    "browser_act",
    "browser_wait",
    "browser_tabs",
    "browser_handoff",
    "browser_commit",
    "browser_developer",
    "agenttab.status",
];
pub const MUTATING_RPC_METHOD_NAMES: &[&str] = &[
    "browser_open",
    "browser_act",
    "browser_handoff",
    "browser_commit",
    "browser_developer",
];
pub const NATIVE_METHOD_NAMES: &[&str] = &[
    "browser_open",
    "browser_snapshot",
    "browser_act",
    "browser_wait",
    "browser_tabs",
    "browser_handoff",
    "browser_commit",
    "browser_developer",
    "commit_review_bind",
    "commit_review_abandon",
];
pub const NATIVE_EVENT_NAMES: &[&str] = &[
    "inventory",
    "ownership_revoked",
    "tab_removed",
    "group_membership_changed",
    "pause_changed",
    "handoff_changed",
    "commit_expired",
    "commit_abandoned",
    "popup_commit_approved",
    "popup_commit_abandoned",
    "extension_disconnected",
];
pub const OUTCOME_NAMES: &[&str] = &[
    "completed",
    "not_started",
    "unknown",
    "needs_user",
    "commit_required",
];
pub const CLIENT_TO_HOST_MAX_BYTES: usize = 1048576;
pub const HOST_TO_CLIENT_MAX_BYTES: usize = 1048576;
pub const HOST_TO_EXTENSION_MAX_BYTES: usize = 1048576;
pub const EXTENSION_TO_HOST_MAX_BYTES: usize = 67108864;

pub const RPC_SCHEMA_ASSETS: &[(&str, &str)] = &[
    (
        "request",
        include_str!("../../../../schemas/rpc/v1/request.schema.json"),
    ),
    (
        "response",
        include_str!("../../../../schemas/rpc/v1/response.schema.json"),
    ),
    (
        "connection",
        include_str!("../../../../schemas/rpc/v1/connection.schema.json"),
    ),
    (
        "browser_open",
        include_str!("../../../../schemas/rpc/v1/browser-open.schema.json"),
    ),
    (
        "browser_snapshot",
        include_str!("../../../../schemas/rpc/v1/browser-snapshot.schema.json"),
    ),
    (
        "browser_act",
        include_str!("../../../../schemas/rpc/v1/browser-act.schema.json"),
    ),
    (
        "browser_wait",
        include_str!("../../../../schemas/rpc/v1/browser-wait.schema.json"),
    ),
    (
        "browser_tabs",
        include_str!("../../../../schemas/rpc/v1/browser-tabs.schema.json"),
    ),
    (
        "browser_handoff",
        include_str!("../../../../schemas/rpc/v1/browser-handoff.schema.json"),
    ),
    (
        "browser_commit",
        include_str!("../../../../schemas/rpc/v1/browser-commit.schema.json"),
    ),
    (
        "browser_developer",
        include_str!("../../../../schemas/rpc/v1/browser-developer.schema.json"),
    ),
    (
        "status",
        include_str!("../../../../schemas/rpc/v1/status.schema.json"),
    ),
];

pub const NATIVE_SCHEMA: &str = include_str!("../../../../schemas/native/v1/message.schema.json");
